### PR TITLE
refactor(ts): enable strict mode; add tslint

### PR DESCRIPTION
**Pull request by VinceOPS**
Hi!

I'd like to propose this PR in order to get more benefits of TypeScript and its typing super powers :smile: .

* enabled [**strict**](https://www.typescriptlang.org/docs/handbook/compiler-options.html) mode
* added TSLint with very basic rules and a npm script (`lint`)
* fixed all the errors reported by `tsc` and `tslint`
* added `.js` files to `.gitignore`

I think it would offer a better base to perform refactoring (removing code duplicates, add more typing, benefit from generics (if appropriate), etc) and add a significant amount of tests.

### CODE REVIEW

**Comment by ThomRick** [comment]
Hey @VinceOPS 
Thanks for the PR !
I'm on it for the merge ;-)

**Comment by VinceOPS** [comment]
Comments/feedback most welcome!

 I initially got into the code for the custom schematic feature request (I need it too), but I'd like to help as much as I can, including in writing unit tests and so on.

Sorry for the (kind of) massive first PR!

**Comment by ThomRick** [comment]
Could you see to change the base branch to be on sprint-1 ?

**Comment by VinceOPS** [comment]
Hi! It shoud be OK now

**Pull request merged**
