### PR TITLE
Added watching non-ts files based on assets

### PR DESCRIPTION
**Pull request by Dominic-Preap**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #581

## What is the new behavior?
Added support watching non-ts file based on assets in `nest-cli.json`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Should we add an option (in `nest-cli.json`) to conditionally disable/enable watching non-ts files in the watch mode?

**Comment by Dominic-Preap** [comment]
What's your opinion? We can have like `watchAssets` in json file and `--watchAssets` in cli. If you agree, I can add it into the code.

```json
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "assets": ["**/*.sql"],
    "watchAssets": true,
    "webpack": false
  }
}
```

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to the docs with this feature :)?

**Comment by Dominic-Preap** [comment]
Sure, I will take a look into that.

**Comment by kamilmysliwiec** [comment]
Thanks! It will be published together with the next release

**Comment by bendadaniel** [comment]
Hello, is there any documantation or sample of this feature please?

**Pull request merged**
