### PR TITLE
feat(cli): Added inspect-brk flag

### PR DESCRIPTION
**Pull request by atjeff**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/nestjs/nest-cli/issues/592

## What is the new behavior?
New flag debug-brk to pass inspect-brk with port or by itself

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR to the docs with this feature? https://github.com/nestjs/docs.nestjs.com

**Comment by atjeff** [comment]
@kamilmysliwiec Yes, I just wanted to make sure you approved of the change first so I wouldn't have to redo the documentation

**Comment by kamilmysliwiec** [comment]
Just merged @atjeff! Feel free to create a PR to the docs if you have some time :)

**Comment by kamilmysliwiec** [comment]
I had to revert this change https://github.com/nestjs/nest-cli/pull/643/files due to this issue https://github.com/nestjs/nest-cli/issues/642

**Comment by atjeff** [comment]
@kamilmysliwiec Sorry about that. I'll try to get a fix up.

**Comment by dannyhuly** [comment]
Hi, any updates about the fix ?

This is a workaround for the meantime (tested using 7.1.2). change `start:debug` script in `package.json` to the following: 
```
nest start --exec 'node --inspect-brk' --watch
```

**Comment by luuktap** [comment]
This exact workaround didn't work for me, using windows (cmd).
Directly executing the following command did the trick:

```
nest start --exec "node --inspect-brk" --watch
```

Thanks @dannyhuly.

**Comment by ruialves92** [comment]
> This exact workaround didn't work for me, using windows (cmd). Directly executing the following command did the trick:
> 
> ```
> nest start --exec "node --inspect-brk" --watch
> ```
> 
> Thanks @dannyhuly.

This worked for me 🙏

**Pull request merged**
