### PR TITLE
fix(deps): using the right package manager to install in `nest generate`

### PR DESCRIPTION
**Pull request by MarvinXu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #1115 

## What is the new behavior?
Using the right package manager to install packages (detecting by lock files)
Snipaste_2023-02-01_15-15-57

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
As described in https://github.com/angular/angular-cli/pull/24305, running the same schematic in `angular-cli` works correctly (using the right package manager)
```
ng new test --no-install
cd test
touch yarn.lock
ng g @nestjs/schematics:resource --name=users --no-dry-run --no-skip-import --language="ts" --source-root="src" --spec --no-flat
```
`nest g` and `ng g` are basicly the same, so we can fix this problem in **cli level** just like `angular-cli`.

If you look into angular's codebase (https://github.com/angular/angular-cli/blob/489d4df0ed17481492728624735a235f25a418db/packages/angular/cli/src/command-builder/schematics-command-module.ts#L116), the `packageManager` option is predefined in `angular-cli` and passed into a `NodeWorkflow`.

In `nest-cli`, we directly use a binary file from `@angular-devkit/schematics-cli` to run our schematics. https://github.com/nestjs/nest-cli/blob/bfd3d8b17a08b0c9bfd8409c6f3a0853f05225b4/lib/runners/schematic.runner.ts#L15
So we just need to implement that _auto-detecting logic_ in this file. 

See PR: https://github.com/angular/angular-cli/pull/24305

### CODE REVIEW

**Comment by micalevisk** [comment]
well done!

I gruess we can wait for the release of v15.2

**Comment by MarvinXu** [comment]
@micalevisk BTW, did you test it, or just review the code? I want to know if there is a good way to test it.

**Comment by micalevisk** [comment]
I didn't tested it

**Comment by kamilmysliwiec** [comment]
dependabot will auto-create a PR with a new version once it's published by the Angular team

**Pull request closed without merging**
