### PR TITLE
feat(watch mode): toggle webpack development mode on watch

### PR DESCRIPTION
**Pull request by ajubin**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: 1318

https://github.com/nestjs/nest-cli/issues/1318

## What is the new behavior?

See issue

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by ajubin** [comment]
Hi, I'm not sure how to test my change directly from the forked code.
I've tried  my fix on my node_modules in my project though.

Is referecing the issue ok for the doc ?

**Comment by ajubin** [comment]
Hi @kamilmysliwiec , is there any reason not to merge this PR ? I can work on it if something is missing :)

**Review by jmcdo29 — APPROVED** [review]
LGTM, we'll wait to hear from Kamil, but the change looks straightforward enough

**Comment by kamilmysliwiec** [comment]
LGTM 

This will be added in the next release

**Pull request merged**
