### PR TITLE
fix: upgrade `os-name` package to fix the macos missing info

### LINKED ISSUE #2400: Unknown OS Version on newer os versions
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Running `nest info` command logs the operating system version as "macOS Unknown." for newer os versions which are not supported by os-name package.

Screenshot 2023-11-24 at 18 24 56

### Minimum reproduction code

N/A

### Steps to reproduce

1. `nest info`

### Expected behavior

macOS Sonoma should be logged as the OS Version.

### Package version

10.2.1

### NestJS version

10.2.10

### Node.js version

21.1.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

_No response_

### PR DESCRIPTION
**Pull request by micalevisk**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: closes #2400 

## What is the new behavior?

`nest info` should work as expected for MacOS

Note that `os-name` has been upgraded to v5 because it has the fix we need. But it requires nodejs v12. The latest version (v6) requires nodejs v18, that's why we aren't using it here

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by chamsou123** [comment]
V5 doesn't support mac Sonoma

**Comment by micalevisk** [comment]
oh, thanks

I don't think we can solve this here then

**Comment by micalevisk** [comment]
@chamsou123 I wonder why v6 works 🤔 

Can you spot something in the diff from v5.1 and v6 here: https://github.com/sindresorhus/os-name/compare/v5.1.0...v6.0.0

**Comment by chamsou123** [comment]
@micalevisk os-name depend on two packages `macos-release` and `windows-release` those two packages are the main part of getting os name, in the last version the author bumped up the versions of those two packages.

**Comment by micalevisk** [comment]
@chamsou123 Do you mind on open an issue in theor repo to request a back-port of that to v5 as a bug fix for those using nodejs16?

Not sure if these two packages requires nodejs 18 as well tho

**Comment by chamsou123** [comment]
@micalevisk 
https://github.com/sindresorhus/os-name/issues/18

**Pull request closed without merging**
