### PR TITLE
fix(cli) support packageManager schematics option

### PR DESCRIPTION
**Pull request by kesslerdev**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

when create a new application the cli doesn't  prompt for package manager before generating files and also doesn't send the right option to schematics

Issue Number: https://github.com/nestjs/schematics/issues/249

## What is the new behavior?

the cli prompt for package manager before generating files and send the correct option `packageManager`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kesslerdev** [comment]
the build script seems broken :/

**Comment by kesslerdev** [comment]
related issue (build failure) 
https://github.com/zkat/npx/issues/100

**Comment by kamilmysliwiec** [comment]
Can you rebase your PR? We switched to CircleCI + different configuration, errors should be gone

**Comment by kesslerdev** [comment]
branch is rebased

**Comment by micalevisk** [comment]
I just tried your fork @kesslerdev well done! Can you please rebase it again?

**Pull request closed without merging**
