### PR TITLE
Add test as cli option for e2e tests

### PR DESCRIPTION
**Pull request by avishayhajbi**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

running tests in monorepo requires calling `npm test` directly

Issue Number: N/A

## What is the new behavior?
implemented a `nest test` command which runs the proper test script for the app, whether in monorepo or not
## Does this PR introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Hey @avishayhajbi! Even though this is a great contribution (thank you!) we don't plan to wrap `test` commands within the CLI in order to avoid having another abstraction layer on top of the existing tooling.

**Comment by moshewe** [comment]
> avoid having another abstraction layer on top of the existing tooling
`nest start` and `nest build` are no different... Also, that's an argument for using `lerna` directly instead of nest monorepo so I'm kinda lost here.

**Comment by kamilmysliwiec** [comment]
Yes, `nest start` and `nest build` are already wrapping some tooling inside. We definitely don't want to wrap even more stuff though

**Comment by kamilmysliwiec** [comment]
Also, `lerna` has different use-cases than NestJS monorepo :) Everyone should pick whatever fits better to project requirements

**Pull request closed without merging**
