### PR TITLE
feat: swc currently support paths mapping on Windows

### PR DESCRIPTION
**Pull request by powerfulyang**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by powerfulyang** [comment]
Detail: https://github.com/swc-project/swc/issues/7806

**Comment by kamilmysliwiec** [comment]
LGTM

**Comment by MinaFayez9** [comment]
Could you please clarify with which version should we expect this to be fixed ?
I already tried the Release 10.1.17 and still facing the same problems that were reported in the referenced issues

**Comment by powerfulyang** [comment]
> Could you please clarify with which version should we expect this to be fixed ? I already tried the Release 10.1.17 and still facing the same problems that were reported in the referenced issues

update your `@swc/core` version to v1.3.81.

or delete your `node_modules` and `package-lock.json` file, reinstall dependencies.

**Comment by MinaFayez9** [comment]
I already had even `@swc/core` version to v1.3.82
I did what you said again now
I even created a fresh project using `nest new` then installed swc then run
Not working

**Comment by powerfulyang** [comment]
@MinaFayez9  error log and minimal reproducible example

**Comment by MinaFayez9** [comment]
I apologize for any inconvenience, but I have already provided the minimal reproduction scenario, which involves creating a new Nest project, adding the SWC, and attempting to run it. These steps are fundamental to setting up a Nest project, and I believe it would be more efficient for you to perform them, as they represent the foundational aspects of project creation.

Regrettably, I perceive this as a bureaucratic process that I am not in favor of. Consequently, I must inform you that I will no longer be actively participating in this discussion, and I will not prioritize running SWC over TSC, as it does not significantly impact the outcome and is more of a nice-to-have feature.

**Comment by BlindKai** [comment]
For those, who are looking for the solution, please, make sure you read the conversation and the comment: https://github.com/swc-project/swc/issues/7806#issuecomment-1699741738

**Pull request merged**
