### PR TITLE
feat: basedir option added to configuration for generate command

### PR DESCRIPTION
**Pull request by yigitkurtcu**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

Issue Number: [#1849](https://github.com/nestjs/nest-cli/issues/1849)

## What is the new behavior?
Added a new option "baseDir". With this new option, new files related to this directory will be created and imported to the app module.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
image

looks like we need to fix our CI

**Comment by wildyaboku** [comment]
Any news on this @micalevisk @yigitkurtcu? Can we re-run the integration tests?

I was investigating because the [official `nest-cli` schema](https://json.schemastore.org/nest-cli) has `baseDir` as an option, but it wasn't working and the generate action had no relevant code. Looks like the PR has not been merged yet.

**Comment by yigitkurtcu** [comment]
Is there any chance the CI have been fixed? Can I do anything about that? @micalevisk

**Comment by micalevisk** [comment]
@yigitkurtcu Not sure. Rebase your push and do a force push to it so it'll rerun the CI

**Comment by yigitkurtcu** [comment]
CI seems to be fixed. @micalevisk

**Review by micalevisk — APPROVED** [review]

**Pull request merged**
