### PR TITLE
fix: Prevent need for double escaping strings

### PR DESCRIPTION
**Pull request by eabrouwer3**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #2242 

The spawn command takes an array of strings, which are no longer escaped and passes them through like this:

```
/Users/me/.local/share/nvm/v18.16.1/bin/node /Users/me/app/dist/main.js json-command --json {"foo": "bar"}
```

## What is the new behavior?

All arguments are passed through quoted so the `spawn` command runs this instead:

```
/Users/me/.local/share/nvm/v18.16.1/bin/node /Users/me/app/dist/main.js "json-command" "--json" "{\\"foo\\": \\"bar\\"}"
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
[x] Maybe?
```

If it's determined that it does, people will just need to replace places where they were doing the double escape (such as `package.json` scripts) and remove the extra escape. For example, change the following:

```
nest start -- json-command --json '\'{"foo": "bar"}\''
```

to

```
nest start -- json-command --json '{"foo": "bar"}'
```

However, since this is basically using a bug as a feature, I'll leave it up to the maintainers to decide if it's actually a breaking change.

### CODE REVIEW

**Comment by eabrouwer3** [comment]
@kamilmysliwiec, who should be added as a reviewer on the PR?

**Review by jmcdo29 — APPROVED** [review]
I think this is fine, this shouldn't affect anything that's non-JSON, so long as it's not like `null` or something like that.

**Review by micalevisk — APPROVED** [review]

**Review by Tony133 — APPROVED** [review]

**Comment by eabrouwer3** [comment]
@kamilmysliwiec just curious on timeline for your review. Thanks!

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
