### PR TITLE
feature(): Add collection parameter to generate and new

### PR DESCRIPTION
**Pull request by LukvonStrom**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Feature

## What is the current behavior?
The Collection which is used is only loaded from the nest config. This means that currently you're unable to create a new Project with a custom collection. Additionally you cannot overwrite the collection which shall be used upon generating a new file in the CLI.

Issue Number: https://github.com/nestjs/nest-cli/issues/99

## What is the new behavior?
`-c` and `--collection` overwrite the Config when using `generate` and overwrite the default Nest Schematics when using `new`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
bumps version to `5.9.0`

### CODE REVIEW

**Comment by LukvonStrom** [comment]
The only problem atm is, that the collection has to be installed in the path where you're executing the command. Didn't found a solution to use a global installed module so far.

**Comment by EmmanuelDemey** [comment]
Hi

We really need this feature for one of our project. 

Have you planned to release it soon ?

Thanks

**Comment by kamilmysliwiec** [comment]
I'll review it shortly. @LukvonStrom could you please resolve conflicts?

**Comment by LukvonStrom** [comment]
@kamilmysliwiec I resolved the conflicts now and I am ready for a review/merge!

**Comment by kamilmysliwiec** [comment]
Thank you!

**Pull request merged**
