### PR TITLE
fix: fail on nest add results in non 0 exit code

### PR DESCRIPTION
**Pull request by stanimirovv**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
```

## What is the current behavior?

Failure to add:

Failure on `add` doesn't return a non zero exit code
```
 npm run build && node bin/nest.js add asd ; echo $?

> @nestjs/cli@8.2.1 build
> tsc

▹▸▹▹▹ Package installation in progress... ☕
Failed to execute command: npm install --save asd@latest
✖ Package installation in progress... ☕
Unable to install library asd because package did not install. Please check package name.
0
```

Issue Number:
It has to do with https://github.com/nestjs/nest-cli/issues/1564 but does not adress the specific issues it has there.

## What is the new behavior?
add fails with a non zero exit code
```
npm run build && node bin/nest.js add asd ; echo $?

> @nestjs/cli@8.2.1 build
> tsc

▹▸▹▹▹ Package installation in progress... ☕
Failed to execute command: npm install --save asd@latest
✖ Package installation in progress... ☕
Unable to install library asd because package did not install. Please check package name.
1
```

## Does this PR introduce a breaking change?
```
[X] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
This doesn't seem to be related to the mentioned issue(?)

**Comment by stanimirovv** [comment]
@kamilmysliwiec it is related since it fixes the rest of it instances where there is an issue with the status code.

I will hapily extend the scope and cover the cases described in the issue, I have already have the context.

My question before I do the implementation is:
Is it okay to add a "global" try/catch in the `bootstrap` function and set the status to 1 (this is what I prefer)

OR

should I track down the different `throw` statements to make sure they eventually get to a catch that sets the status to 1 ?

**Comment by kamilmysliwiec** [comment]
I'd start by making sure that `nest build` always exits with the status set to 1 when build fails (as this is the most crucial fix atm) and then we can think if there are any other improvements we should/could make

**Comment by stanimirovv** [comment]
@micalevisk @kamilmysliwiec ready for review

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
