### PR TITLE
bugfix(cli) use outDir from asset item instead of the default one

### PR DESCRIPTION
**Pull request by lijax**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

assets will be copied to the default outDir of the app.

## What is the new behavior?

will be copied to the outDir of each item

```
        "org-api": {
            "type": "application",
            "root": "apps/org-api",
            "entryFile": "main",
            "sourceRoot": "apps/org-api/src",
            "compilerOptions": {
                "tsConfigPath": "apps/org-api/tsconfig.app.json",
                "assets": [{
                    "include": "../client/**/*",
                    "outDir": "dist/apps/org-api/apps/org-api/client/"
                }]
            }
        }
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
`outDir` from `nest-cli` is used by schematics to indicate where to generate files, while `outDir` used by `assets` is extracted from `tsconfig.app.json`/`tsconfig.json` file. Just ensure that your `tsconfig` has a proper `outDir` configured

**Comment by lijax** [comment]
But when copying the assets, outDir from assets isn't actually working. It's still using the one for the app.

**Comment by kamilmysliwiec** [comment]
That means we're reading the wrong `tsconfig` file(?). Would you like to investigate this?

**Comment by lijax** [comment]
No. The config was reading correctly. It's because when iterating and copying the asset items, the app outDir was used instead.

**Comment by kamilmysliwiec** [comment]
You're completely right. Sorry @lijax!

Thank you for your contribution!

**Pull request merged**
